### ISSUE TITLE
M2Stack Core2 v1.1 Support

### ISSUE THREAD

**Issue by idiig** [palette-system/az-m5ortho#3]
Can M2Stack Core2 v1.1 function well for the keyboard?

https://www.switch-science.com/products/9349

**Comment by palette-system** [comment]
It will probably work.
However, as we have not performed any operational tests, we cannot guarantee operation.

**Comment by idiig** [comment]
Hi, thank you for your response.
I used the link https://azkey.jp/azm5ortho/ to install the firmware into the M2Stack.
The installation succeeded, but the device froze.

Then I tried the code in https://github.com/palette-system/az-m5ortho/tree/main/firmware/az_keyboard, where I got an error showing that `wirelib.h` was not in the path as follows:

```
In file included from C:\Users\idiig\Downloads\az-m5ortho-main\az-m5ortho-main\firmware\az_keyboard\az_keyboard.ino:4:
C:\Users\idiig\Downloads\az-m5ortho-main\az-m5ortho-main\firmware\az_keyboard\az_common.h:23:10: fatal error: src/lib/wirelib.h: No such file or directory
 #include "src/lib/wirelib.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: src/lib/wirelib.h: No such file or directory
```

Can you upload ``wirelib.h`?

I also tried to compile `m5stack_mcp23017_simple.ino`. This works with  the M5Core2 library version 0.1.9.
So I think building the firmware with M2Core2 v0.1.9 first and installing it into the M5Stack Core 2 v1.1 is feasible. 

PS:  files in https://github.com/palette-system/az-m5ortho/tree/main/firmware/lv_arduino was copied to the path.

**Comment by palette-system** [comment]
Sorry, I'll try it myself when I have time.
The missing file may be here.

https://github.com/palette-system/az-core/blob/main/firmware/az_keyboard/src/lib/wirelib.h
https://github.com/palette-system/az-core/blob/main/firmware/az_keyboard/src/lib/wirelib.cpp

**Comment by idiig** [comment]
Thank you for the confirmation! I have tried the sketch.
The installation succeeded and the monitor worked well.
But touching key switches seems not to have a reaction.

When I start up the device, the display showed:

```
...
Adafruit_MCP23X17
begin_i2c 0 32 NG
begin_i2c 1 32 NG
begin_i2c 2 32 NG
begin_i2c 3 32 NG
```

I think there could be because of power supply problems, or other compatibility issues.

Anyway, thank you for you attention!

**Comment by palette-system** [comment]
https://github.com/palette-system/az-m5ortho/tree/main/firmware

**Comment by palette-system** [comment]
I also confirmed that it doesn't work with the current sources.
Please wait while we fix it
I will fix it soon

**Comment by palette-system** [comment]
@idiig 

I found out the reason why I couldn't get the key input.
We apologize for the delay in identifying the cause.
The cause was that when I passed true to initialize I2C in the fourth parameter of M5.begin, the I2C initialization I had performed was not performed.
By setting this parameter to false, key input is now possible, so please check it out.

https://github.com/palette-system/az-m5ortho/commit/882e639ae41b1162f51e2697660d7b27da72a4b8

In addition, we plan to upload bin files compiled with the latest code to the repository in the near future.

**Comment by palette-system** [comment]
Uploaded version 0.2.21

https://azkey.jp/azm5ortho/

**Comment by idiig** [comment]
Thank you! I will try it out
